# Import data

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#plt.style.use("v_paper")
import deepdish as dd
from scipy.signal import savgol_filter
import statsmodels as sm
%matplotlib inline
from scipy import stats
import statsmodels.stats.api as sms
import statsmodels.stats.power as ssp
import scipy

In [80]:
esum = dd.io.load("experiments_summary.h5")

lobe_data = pd.DataFrame(esum["lobe_summary"])

lobe_activities = np.row_stack(esum["df_fs"])

lobe_data["df_f"] = np.mean(lobe_activities[:, 31:35], 1)

In [81]:
lobe_data_w_vinegar=lobe_data

In [82]:
lobe_data=lobe_data[lobe_data["stimulus"]!="high_Vinegar"]

In [83]:
valence_map = {
"high_Vinegar": np.nan,
"Vinegar": '1',
"Yeast": '1',
"Isoamylacetate": np.nan,
"2-Heptanone": np.nan,
"1-Heptanone": np.nan,
    
"cVA": np.nan,
        "3Octanol": np.nan,
        "Ethanol": np.nan,

"1-Hexanol": np.nan,
"Peppermint": '-1',
"4MCH": np.nan,
"Citronella": '-1',
"Geosmin": '-1',
}

lobe_data["valence"] = [valence_map[s] for s in lobe_data.stimulus]

C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [84]:
lobe_data["valence"] = [valence_map[s] for s in lobe_data.stimulus]

C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [85]:
lobe_data.stimulus.unique()

array(['Citronella', 'Vinegar', 'Yeast', 'Peppermint', '1-Heptanone',
       '1-Hexanol', 'cVA', 'Geosmin', '4MCH', 'Isoamylacetate',
       '2-Heptanone', '3Octanol', 'Ethanol'], dtype=object)

In [86]:
Lobes=lobe_data.lobe.unique()
Lobes

array(['a1', 'a2', 'a3', 'ap1', 'ap2', 'ap3', 'b1', 'b2', 'bp1', 'bp2',
       'g1', 'g2', 'g3', 'g4', 'g5'], dtype=object)

In [87]:
lobe_data

experiment_id    stimulus valence  \
0                     TH-58E02_090816_Citronella  Citronella      -1   
1                     TH-58E02_090816_Citronella  Citronella      -1   
2                     TH-58E02_090816_Citronella  Citronella      -1   
3                     TH-58E02_090816_Citronella  Citronella      -1   
4                     TH-58E02_090816_Citronella  Citronella      -1   
5                     TH-58E02_090816_Citronella  Citronella      -1   
6                     TH-58E02_090816_Citronella  Citronella      -1   
7                     TH-58E02_090816_Citronella  Citronella      -1   
8                     TH-58E02_090816_Citronella  Citronella      -1   
9                     TH-58E02_090816_Citronella  Citronella      -1   
10                    TH-58E02_090816_Citronella  Citronella      -1   
11                    TH-58E02_090816_Citronella  Citronella      -1   
12                    TH-58E02_090816_Citronella  Citronella      -1   
13                    TH-58E02_090816_Citronella  Citronella      -1   
14                    TH-58E02_090816_Citronella  Citronella      -1   
15                       TH-58E02_090816_Vinegar     Vinegar       1   
16                       TH-58E02_090816_Vinegar     Vinegar       1   
17                       TH-58E02_090816_Vinegar     Vinegar       1   
18                       TH-58E02_090816_Vinegar     Vinegar       1   
19                       TH-58E02_090816_Vinegar     Vinegar       1   
20                       TH-58E02_090816_Vinegar     Vinegar       1   
21                       TH-58E02_090816_Vinegar     Vinegar       1   
22                       TH-58E02_090816_Vinegar     Vinegar       1   
23                       TH-58E02_090816_Vinegar     Vinegar       1   
24                       TH-58E02_090816_Vinegar     Vinegar       1   
25                       TH-58E02_090816_Vinegar     Vinegar       1   
26                       TH-58E02_090816_Vinegar     Vinegar       1   
27                       TH-58E02_090816_Vinegar     Vinegar       1   
28                       TH-58E02_090816_Vinegar     Vinegar       1   
29                       TH-58E02_090816_Vinegar     Vinegar       1   
...                                          ...         ...     ...   
5850  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5851  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5852  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5853  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5854  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5855  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5856  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5857  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5858  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5859  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5860  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5861  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5862  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5863  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5864  200214_0_TH58E02G6f_ST00_0_cVAMated_Single         cVA     NaN   
5865  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5866  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5867  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5868  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5869  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5870  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5871  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5872  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
5873  200214_0_TH58E02G6f_ST00_1_cVAMated_Single         cVA     NaN   
587

In [88]:
data_tastequi=pd.read_excel("Taste_data.xlsx",'quinine').transpose()

data_tastesuc=pd.read_excel("Taste_data.xlsx",'sucrose').transpose()

db1=data_tastesuc.stack().reset_index()

db2=data_tastequi.stack().reset_index()

#taste_mean=pd.concat([suc_mean,qui_mean], ignore_index=True, sort=False)

db2['taste']='quinine'
db1['taste']='sucrose'

data_taste = pd.concat([db1, db2], ignore_index=True, sort=False)

data_taste.columns = ['lobe', 'num','df_f','taste']

data_taste['df_f_norm']=0
data_taste['norm']=0

Nums=[170,110,29,177,176,173,188,151,174,175,168,170]

for taste in ['quinine', 'sucrose']:
    for i in Nums:
        if any((data_taste['num']==i) & (data_taste['taste']==taste)):
            subData=data_taste[data_taste['num']==i][data_taste['taste']==taste]
            Norm=np.float(subData[subData['lobe']=='Mean'].df_f)
            data_taste.loc[(data_taste['num']==i) & (data_taste['taste']==taste),'norm']=Norm


data_taste.df_f_norm=data_taste.df_f-data_taste.norm

C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
C:\Users\aimon\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: UserWarning: Boolean Series key will be reindexed to match Da

# Get individual p values

In [89]:
ptaste=np.zeros(15)
i=0
for lobe in Lobes:
    lobe_datab=data_taste[data_taste['lobe']==lobe]
    sub_lobe_data_suc=lobe_datab[lobe_datab['taste']=='sucrose'].dropna()
    sub_lobe_data_qui=lobe_datab[lobe_datab['taste']=='quinine'].dropna()
    test=scipy.stats.mannwhitneyu(sub_lobe_data_suc["df_f_norm"], sub_lobe_data_qui["df_f_norm"], alternative='two-sided')
    ptaste[i]=test[1]
    i=i+1
    if i==14:
        EffectSize=(np.mean(sub_lobe_data_suc["df_f_norm"])-np.mean(sub_lobe_data_qui["df_f_norm"]))/np.sqrt((np.std(sub_lobe_data_suc["df_f_norm"])*np.std(sub_lobe_data_suc["df_f_norm"])+np.std(sub_lobe_data_qui["df_f_norm"])*np.std(sub_lobe_data_qui["df_f_norm"]))/2)
print(EffectSize)
print(ptaste)

1.268018547587858
[2.29048669e-01 2.30331068e-01 1.75244245e-01 6.35507924e-04
 2.94893634e-02 9.48532517e-01 2.70344141e-01 1.99644533e-02
 8.14043842e-03 7.50492347e-02 9.21779735e-03 6.35507924e-04
 8.09894130e-01 1.41379695e-02 8.14043842e-03]


In [90]:
power_analysis = ssp.TTestIndPower()
power_analysis.solve_power(effect_size = EffectSize, 
                                         power = 0.8, 
                                         alpha = 0.05/60)

24.60099835246706

In [91]:
Pcorrecttaste=sm.stats.multitest.multipletests(ptaste, alpha=0.05, method='simes-hochberg', is_sorted=False, returnsorted=False)
Pcorrecttaste

(array([False, False, False,  True, False, False, False, False, False,
        False, False,  True, False, False, False]),
 array([0.81103242, 0.81103242, 0.81103242, 0.00889711, 0.23591491,
        0.94853252, 0.81103242, 0.17968008, 0.09768526, 0.52534464,
        0.10139577, 0.00889711, 0.94853252, 0.14137969, 0.09768526]),
 0.0034137129465903193,
 0.0033333333333333335)

In [92]:
pvinegar=np.zeros(15)
i=0
for lobe in Lobes:
    lobe_datab=lobe_data_w_vinegar[lobe_data_w_vinegar['lobe']==lobe]
    sub_lobe_data=lobe_datab[lobe_datab.hours_starved.isin({24,48})]
    sub_lobe_data_low=sub_lobe_data[sub_lobe_data['stimulus']=='Vinegar']
    sub_lobe_data_high=sub_lobe_data[sub_lobe_data['stimulus']=='high_Vinegar']
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_low["df_f"], sub_lobe_data_high["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pvinegar[i]=test[1]
    i=i+1

In [93]:
pvinegar

array([8.45734860e-03, 3.17568771e-02, 3.42634004e-02, 1.47936088e-02,
       2.93710199e-02, 5.86712432e-01, 1.96090923e-02, 7.55365319e-01,
       5.00619885e-05, 4.24247127e-02, 6.16181690e-04, 8.05840557e-04,
       5.68019188e-03, 3.94076568e-01, 3.40718536e-01])

In [170]:
pstarvation=np.zeros(15)
i=0
for lobe in Lobes:
    sub_lobe_data=lobe_data[lobe_data['lobe']==lobe]
    sub_lobe_data_fed=sub_lobe_data[sub_lobe_data['hours_starved']==0]
    sub_lobe_data_starved=sub_lobe_data[sub_lobe_data['hours_starved']!=0]
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_fed["df_f"], sub_lobe_data_starved["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pstarvation[i]=test[1]
    i=i+1

In [191]:
pstarvation

array([1.41609298e-04, 3.05863011e-01, 4.87579246e-01, 3.27523330e-01,
       1.92965502e-01, 7.60297789e-01, 1.31502792e-07, 1.92154488e-02,
       4.09091560e-02, 1.39320616e-08, 5.77910304e-03, 1.80259891e-01,
       6.30804719e-01, 1.41274742e-04, 1.44219345e-02])

In [171]:
pstarvationpre=np.zeros(15)
i=0
for lobe in Lobes:
    sub_lobe_data=lobe_data[lobe_data['lobe']==lobe]
    sub_lobe_data_fed=sub_lobe_data[sub_lobe_data['hours_starved']==0]
    sub_lobe_data_starved=sub_lobe_data[sub_lobe_data['hours_starved']!=0]
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_fed["single_pre_amp"], sub_lobe_data_starved["single_pre_amp"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pstarvationpre[i]=test[1]
    i=i+1

In [172]:
pstarvationpre

array([4.32993583e-01, 8.66542932e-01, 2.52132563e-01, 4.22552344e-01,
       7.68155961e-02, 4.05430781e-01, 5.10287534e-03, 9.23688568e-01,
       2.32473435e-03, 9.53196063e-01, 6.53686020e-02, 3.96443047e-01,
       6.05637866e-04, 9.77731211e-02, 6.51272229e-01])

In [173]:
pvalence=np.zeros(15)
i=0
for lobe in Lobes:
    sub_lobe_data=lobe_data[lobe_data['lobe']==lobe]
    sub_lobe_data_pos=sub_lobe_data[sub_lobe_data['valence']=='1']
    sub_lobe_data_neg=sub_lobe_data[sub_lobe_data['valence']=='-1']
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_pos["df_f"], sub_lobe_data_neg["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pvalence[i]=test[1]        
    i=i+1    

In [174]:
pvalence

array([1.79157173e-01, 6.65884731e-02, 1.28705244e-03, 8.70822176e-04,
       7.16932612e-02, 6.36761177e-01, 9.39891384e-03, 1.29232889e-05,
       4.61072450e-01, 1.03005787e-08, 8.92481883e-01, 3.91271983e-04,
       6.98572635e-01, 1.32704193e-09, 4.20268851e-03])

In [175]:
pmated=np.zeros(15)
i=0
lobe_datacVA=lobe_data[lobe_data['stimulus']=='cVA']
for lobe in Lobes:
    sub_lobe_data=lobe_datacVA[lobe_datacVA['lobe']==lobe]
    sub_lobe_data_pos=sub_lobe_data[sub_lobe_data['virgin']==True]
    sub_lobe_data_neg=sub_lobe_data[sub_lobe_data['virgin']==False]
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_pos["df_f"], sub_lobe_data_neg["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pmated[i]=test[1]   
    if i==8:
        EffectSize=(np.mean(sub_lobe_data_pos["df_f"])-np.mean(sub_lobe_data_neg["df_f"]))/np.sqrt((np.std(sub_lobe_data_pos["df_f"])*np.std(sub_lobe_data_pos["df_f"])+np.std(sub_lobe_data_neg["df_f"])*np.std(sub_lobe_data_neg["df_f"]))/2)
    i=i+1   
print(pmated)
print(EffectSize)

[0.8245302  0.17546656 0.02543717 0.31927636 0.15504931 0.19824472
 0.91005169 0.51172304 0.00557761 0.11150696 0.79916179 0.13917524
 0.08803574 0.43223066 0.94825152]
-0.7179123059766884


In [213]:
pmatedAll=0
i=0
lobe_datacVA=lobe_data[lobe_data['stimulus']=='cVA']
sub_lobe_data=lobe_datacVA
sub_lobe_data_pos=sub_lobe_data[sub_lobe_data['virgin']==True]
sub_lobe_data_neg=sub_lobe_data[sub_lobe_data['virgin']==False]
test=sm.stats.weightstats.ttest_ind(sub_lobe_data_pos["df_f"], sub_lobe_data_neg["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
pmatedAll=test[1]   
EffectSize=(np.mean(sub_lobe_data_pos["df_f"])-np.mean(sub_lobe_data_neg["df_f"]))/np.sqrt((np.std(sub_lobe_data_pos["df_f"])*np.std(sub_lobe_data_pos["df_f"])+np.std(sub_lobe_data_neg["df_f"])*np.std(sub_lobe_data_neg["df_f"]))/2)
MeanDiff=np.mean(sub_lobe_data_pos["df_f"])-np.mean(sub_lobe_data_neg["df_f"])
STE=np.sqrt((np.std(sub_lobe_data_pos["df_f"])*np.std(sub_lobe_data_pos["df_f"])+np.std(sub_lobe_data_neg["df_f"])*np.std(sub_lobe_data_neg["df_f"]))/2)
print(np.std(sub_lobe_data_pos["df_f"]))
print(pmatedAll)
print(MeanDiff)
print(STE)

0.43364517726294727
8.524146045904948e-05
-0.12193846329770242
0.4840764830025369


In [176]:
import statsmodels.stats.power as ssp
power_analysis = ssp.TTestIndPower()
power_analysis.solve_power(effect_size = EffectSize, 
                                         power = 0.8, 
                                         alpha = 0.05/60)

70.7099373140391

In [177]:
pmatedsingle=np.zeros(15)
i=0
lobe_datacVA=lobe_data[lobe_data['stimulus']=='cVA']
for lobe in Lobes:
    sub_lobe_data=lobe_datacVA[lobe_datacVA['lobe']==lobe]
    sub_lobe_data_pos=sub_lobe_data[sub_lobe_data['virgin']==True]
    sub_lobe_data_neg1=sub_lobe_data[sub_lobe_data['virgin']==False]
    sub_lobe_data_neg=sub_lobe_data_neg1[sub_lobe_data_neg1['mated_single']=='Mated_Single']
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_pos["df_f"], sub_lobe_data_neg["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pmatedsingle[i]=test[1]    
    if i==8:
        EffectSize=(np.mean(sub_lobe_data_pos["df_f"])-np.mean(sub_lobe_data_neg["df_f"]))/np.sqrt((np.std(sub_lobe_data_pos["df_f"])*np.std(sub_lobe_data_pos["df_f"])+np.std(sub_lobe_data_neg["df_f"])*np.std(sub_lobe_data_neg["df_f"]))/2)
    i=i+1   
print(pmatedsingle)
print(EffectSize)

[2.89933427e-01 5.11938060e-01 6.41934623e-02 4.00660289e-01
 3.49354318e-01 8.08533589e-01 5.15989697e-01 6.73033631e-02
 3.67530495e-03 6.79546180e-04 1.76118035e-01 3.94556293e-01
 7.42403949e-02 1.94888018e-01 3.04178133e-01]
-1.1889344501064638


In [178]:
power_analysis.solve_power(effect_size = EffectSize, 
                                         power = 0.8, 
                                         alpha = 0.05/60)

27.588660532628484

In [179]:
power_analysis.solve_power(effect_size = EffectSize, 
                                         power = 0.8, 
                                         alpha = 0.05)

12.144692649885506

In [180]:
pmatedpre=np.zeros(15)
i=0
lobe_datacVA=lobe_data[lobe_data['stimulus']=='cVA']
for lobe in Lobes:
    sub_lobe_data=lobe_datacVA[lobe_datacVA['lobe']==lobe]
    sub_lobe_data_pos=sub_lobe_data[sub_lobe_data['virgin']==True]
    sub_lobe_data_neg=sub_lobe_data[sub_lobe_data['virgin']==False]
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_pos["single_pre_amp"], sub_lobe_data_neg["single_pre_amp"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pmatedpre[i]=test[1]        
    i=i+1   
print(pmatedpre)

[0.69196143 0.35104421 0.8038141  0.38062589 0.00240065 0.507416
 0.34855768 0.94010195 0.94552615 0.74400559 0.00914743 0.69181784
 0.9566616  0.02987246 0.18881935]


In [181]:
pdorsaltoventral=np.zeros(15)
i=0
for lobe in Lobes:
    sub_lobe_data=lobe_data[lobe_data['lobe']==lobe]
    sub_lobe_data_up=sub_lobe_data[sub_lobe_data['dorsal_to_ventral']==0]
    sub_lobe_data_down=sub_lobe_data[sub_lobe_data['dorsal_to_ventral']!=0]
    test=sm.stats.weightstats.ttest_ind(sub_lobe_data_up["df_f"],sub_lobe_data_down["df_f"], alternative='two-sided', usevar='pooled', weights=(None, None), value=0)
    pdorsaltoventral[i]=test[1]
    i=i+1

# Multiple comparison

Simes-hochberg: roughly 5% of results would report as false positives

In [205]:
Pcorrect=sm.stats.multitest.multipletests(np.concatenate((pstarvation,pvalence,pmated,pvinegar,pstarvationpre,pdorsaltoventral)), alpha=0.05, method='simes-hochberg', is_sorted=False, returnsorted=False)

In [193]:
#Pcorrect=sm.stats.multitest.multipletests(np.concatenate((pstarvation,pvalence,pmated,ptaste)), alpha=0.05, method='simes-hochberg', is_sorted=False, returnsorted=False)

In [194]:
#starvation
print(Pcorrect[1][range(3)])
print(Pcorrect[1][range(3,6)])
print(Pcorrect[1][range(6,8)])
print(Pcorrect[1][range(8,10)])
print(Pcorrect[1][range(10,15)])

[0.01147035 0.95319606 0.95319606]
[0.95319606 0.95319606 0.95319606]
[1.14407429e-05 9.53196063e-01]
[9.53196063e-01 1.22602142e-06]
[0.39875811 0.95319606 0.95319606 0.01147035 0.95184768]


In [195]:
#print(Pcorrectpre[1][range(3)])
#print(Pcorrectpre[1][range(3,6)])
#print(Pcorrectpre[1][range(6,8)])
#print(Pcorrectpre[1][range(8,10)])
#print(Pcorrectpre[1][range(10,15)])

In [196]:
#valence
Pcorrect[1][range(15,30)]
print(Pcorrect[1][range(15,30)][range(3)])
print(Pcorrect[1][range(15,30)][range(3,6)])
print(Pcorrect[1][range(15,30)][range(6,8)])
print(Pcorrect[1][range(15,30)][range(8,10)])
print(Pcorrect[1][range(15,30)][range(10,15)])

[0.95319606 0.95319606 0.09652893]
[0.06618249 0.95319606 0.95319606]
[0.62972723 0.00109848]
[9.53196063e-01 9.16751504e-07]
[9.53196063e-01 3.13017586e-02 9.53196063e-01 1.19433774e-07
 3.06796262e-01]


In [197]:
#mated
Pcorrect[1][range(30,45)]
print(Pcorrect[1][range(30,45)][range(3)])
print(Pcorrect[1][range(30,45)][range(3,6)])
print(Pcorrect[1][range(30,45)][range(6,8)])
print(Pcorrect[1][range(30,45)][range(8,10)])
print(Pcorrect[1][range(30,45)][range(10,15)])

[0.95319606 0.95319606 0.95319606]
[0.95319606 0.95319606 0.95319606]
[0.95319606 0.95319606]
[0.39601011 0.95319606]
[0.95319606 0.95319606 0.95319606 0.95319606 0.95319606]


In [198]:
#vinegar
Pcorrect[1][range(45,60)]
print(Pcorrect[1][range(45,60)][range(3)])
print(Pcorrect[1][range(45,60)][range(3,6)])
print(Pcorrect[1][range(45,60)][range(6,8)])
print(Pcorrect[1][range(45,60)][range(8,10)])
print(Pcorrect[1][range(45,60)][range(10,15)])

[0.57509971 0.95319606 0.95319606]
[0.95319606 0.95319606 0.95319606]
[0.95319606 0.95319606]
[0.00415515 0.95319606]
[0.04806217 0.06204972 0.39761343 0.95319606 0.95319606]


In [199]:
#starvationpre
Pcorrect[1][range(60,75)]

array([0.95319606, 0.95319606, 0.95319606, 0.95319606, 0.95319606,
       0.95319606, 0.36740702, 0.95319606, 0.17203034, 0.95319606,
       0.95319606, 0.95319606, 0.04784539, 0.95319606, 0.95319606])

In [200]:
#pdorsaltoventral
Pcorrect[1][range(75,90)]

array([9.53196063e-01, 2.57779040e-04, 9.53196063e-01, 9.53196063e-01,
       2.95748816e-03, 9.53196063e-01, 9.53196063e-01, 9.53196063e-01,
       9.53196063e-01, 9.53196063e-01, 9.53196063e-01, 9.53196063e-01,
       9.53196063e-01, 9.53196063e-01, 9.53196063e-01])

In [161]:
#pdorsaltoventral
Pcorrect[1][range(90,105)]

IndexError: index 90 is out of bounds for axis 0 with size 90

In [162]:
#ptaste
Pcorrect[1][range(105,120)]

IndexError: index 105 is out of bounds for axis 0 with size 90

Old stuff

In [ ]:
lobe_data["adaptnorm"] = -lobe_data.adaptation/lobe_data.df_mean
lobe_data.adaptnorm[lobe_data.df_mean<0.3]=np.nan
lobe_data["adaptnormperc"]=lobe_data.adaptnorm*100

In [ ]:
padapt=np.zeros(15)

i=0
for lobe in Lobes:
    sub_lobe_data=lobe_data[lobe_data['lobe']==lobe]["adaptnormperc"]
    data_to_test=np.array([x for x in sub_lobe_data if str(x) != 'nan'])
    test=stats.ttest_1samp(data_to_test, 0)
    print(sms.DescrStatsW(data_to_test).tconfint_mean())
    padapt[i]=test[1]
    i=i+1